'use client'

import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'
import {
  Search, Zap, Shield, Accessibility,
  Smartphone, Layers, Brain, TrendingUp,
  AlertTriangle, FileText, ArrowRight
} from 'lucide-react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

const features = [
  {
    icon: Search,
    title: 'SEO Audit',
    description: 'Meta tags, structured data, crawlability, keyword gaps, backlink profile analysis.',
    color: '#6366f1',
    bg: 'rgba(99,102,241,0.08)',
    border: 'rgba(99,102,241,0.15)',
  },
  {
    icon: Zap,
    title: 'Performance Audit',
    description: 'Core Web Vitals, LCP, CLS, FID, page speed, render-blocking resources.',
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.08)',
    border: 'rgba(245,158,11,0.15)',
  },
  {
    icon: Shield,
    title: 'Security Audit',
    description: 'SSL/TLS health, HTTPS redirects, HTTP headers, vulnerability exposure check.',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.08)',
    border: 'rgba(16,185,129,0.15)',
  },
  {
    icon: Accessibility,
    title: 'Accessibility',
    description: 'WCAG 2.1 compliance, contrast ratios, keyboard navigation, ARIA attributes.',
    color: '#8b5cf6',
    bg: 'rgba(139,92,246,0.08)',
    border: 'rgba(139,92,246,0.15)',
  },
  {
    icon: Smartphone,
    title: 'Mobile Optimization',
    description: 'Responsive layout, touch targets, mobile load times, viewport configuration.',
    color: '#ec4899',
    bg: 'rgba(236,72,153,0.08)',
    border: 'rgba(236,72,153,0.15)',
  },
  {
    icon: Layers,
    title: 'UX Review',
    description: 'Navigation clarity, CTA placement, conversion blockers, user journey analysis.',
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.08)',
    border: 'rgba(6,182,212,0.15)',
  },
  {
    icon: Brain,
    title: 'AI Recommendations',
    description: 'Prioritized, plain-English fixes generated by our AI — not generic checklists.',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.15)',
  },
  {
    icon: TrendingUp,
    title: 'Growth Opportunities',
    description: 'Untapped traffic sources, conversion improvements, and revenue-driving insights.',
    color: '#34d399',
    bg: 'rgba(52,211,153,0.08)',
    border: 'rgba(52,211,153,0.15)',
  },
  {
    icon: AlertTriangle,
    title: 'Priority Fixes',
    description: 'Critical issues ranked by revenue impact so you know exactly where to start.',
    color: '#fb923c',
    bg: 'rgba(251,146,60,0.08)',
    border: 'rgba(251,146,60,0.15)',
  },
  {
    icon: FileText,
    title: 'Professional PDF Report',
    description: 'A polished, shareable report your team or developer can act on immediately.',
    color: '#60a5fa',
    bg: 'rgba(96,165,250,0.08)',
    border: 'rgba(96,165,250,0.15)',
  },
]

export default function WhatIncluded() {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true, margin: '-80px' })

  return (
    <section id="included" ref={ref} className="section-padding relative overflow-hidden">
      {/* Bg decoration */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-px h-32 bg-gradient-to-b from-transparent via-indigo-500/30 to-transparent" />

      <div className="relative max-w-7xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <p className="text-xs font-semibold text-indigo-400 uppercase tracking-[0.2em] mb-3">Everything covered</p>
          <h2 className="text-4xl sm:text-5xl font-black text-white tracking-tight mb-4">
            What&apos;s Included
          </h2>
          <p className="text-white/40 text-lg max-w-xl mx-auto leading-relaxed">
            Every report covers 10 critical areas of your website. No corner left unexamined.
          </p>
        </motion.div>

        {/* Feature grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 24 }}
              animate={inView ? { opacity: 1, y: 0 } : {}}
              transition={{ delay: i * 0.06, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              className={`group glass-card p-5 flex flex-col gap-3 hover:-translate-y-1 hover:border-white/[0.12] transition-all duration-300 cursor-default ${
                i >= 8 ? 'sm:col-span-1 lg:col-span-1' : ''
              }`}
            >
              {/* Icon */}
              <div
                className="w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 transition-transform duration-300 group-hover:scale-110"
                style={{ background: feature.bg, border: `1px solid ${feature.border}` }}
              >
                <feature.icon className="w-4 h-4" style={{ color: feature.color }} />
              </div>

              {/* Content */}
              <div>
                <h3 className="text-sm font-semibold text-white mb-1.5">{feature.title}</h3>
                <p className="text-xs text-white/35 leading-relaxed">{feature.description}</p>
              </div>

              {/* Hover indicator */}
              <div
                className="h-px w-0 group-hover:w-full transition-all duration-300 rounded-full"
                style={{ background: `linear-gradient(90deg, ${feature.color}, transparent)` }}
              />
            </motion.div>
          ))}
        </div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.8, duration: 0.6 }}
          className="text-center mt-14"
        >
          <Button asChild size="lg" variant="premium">
            <Link href="/order">
              Get All This For Your Site
              <ArrowRight className="w-4 h-4" />
            </Link>
          </Button>
          <p className="text-white/25 text-sm mt-3">Starting at $10 · PDF delivered in 24 hours</p>
        </motion.div>
      </div>
    </section>
  )
}
